conquistadors/config/routes.rb
Rails.application.routes.draw do

  resources :trade_deals

  # get '/blah' => 'static#blah'
  root to: 'static#index'

  # resources :countries

  post '/login' => :login, controller: :players
  delete '/login' => :logout, controller: :players
  resources :players do
    # get ':param' => :show, on: :member
    resources :countries
  end

  

end

conquistadors/app/models/player.rb
class Player < ActiveRecord::Base


  # Secure Session
  # def generate_token
  #   self.token = SecureRandom.urlsafe_base64
  # end

  has_secure_password 
  has_one :country, dependent: :destroy
  has_many :trade_deals

  validates :email, :password_digest, presence: :true
  validates :email, uniqueness: :true

  def self.find_by_trade_deal(deal)
    country_resource = CountryResource.find(deal.country_resource_id)
    country = Country.find(country_resource.country_id)
    player =Player.find(country.player_id)
  end
  
end

conquistadors/app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end


  def login
    @player = Player.find_by_email(params[:email])
    if @player && @player.authenticate(params[:password])
      session[:player_id] = @player.id
      if @player.country
        redirect_to player_country_path(@player, @player.country.id)
      else
        redirect_to new_player_country_path(@player)
      end
    else
      render :new, notice: 'Invalid Login'
    end
  end

  def logout
    reset_session
    redirect_to new_player_path, notice: 'You have been logged out'
  end

  # GET /players/1
  # GET /players/1.json
  def show
    # @country = Country.find_by(player_id: current_player.id)
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
    @player = current_player
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)
    respond_to do |format|
      if @player.save
        session[:player_id] = @player.id
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :title, :email, :password, :password_confirmation)
    end
end

conquistadors/app/helpers/players_helper.rb
module PlayersHelper
end

conquistadors/app/views/players/_form.html.erb
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </div>
  <div class="field">
    <%= form.label :password %><br>
    <%= form.password_field :password %>
  </div>
  <div class="field">
    <%= form.label :password_confirmation %><br>
    <%= form.password_field :password_confirmation %>
  </div>

conquistadors/app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= form_for(@player) do |form| %> 
  <%= render form %>
  <div class="actions">
    <%= form.submit "update player" %>
  </div>
<% end %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

conquistadors/app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Players</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= player.title %></td>
        <% if player.country %>
        <!-- remove png from country name listing -->
          <td><%= link_to player.country.name.split('.')[0], player_country_path(player, player.country) %></td>
        <% end %>

        <% if player == current_player %>
          <td><%= link_to 'My Page', player %></td>
          <td><%= link_to 'Edit', edit_player_path(player) %></td>
          <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

conquistadors/app/views/players/new.html.erb
<div class="container">
    <% if notice %><div class="notice"><%= notice %></div><% end %>
    <div class="row">
        <div class="six columns">
            <h1>Sign Up</h1>

            <%= form_for(@player) do |form| %>
                <%= render form %>
                  <div class="actions">
                    <%= form.submit "create" %>
                  </div>
           <% end %>
        </div>

        <div class="six columns">
            <h1>Log In</h1>
            <%= form_tag login_path, method: 'post' do |form| %>
                <div id="players_login">
                    <div class="row">
                        <div class="three columns"><%= label_tag :email %></div>
                        <div class="nine columns"><%= text_field_tag :email, params[:email], class: 'u-full-width' %></div>
                    </div>
                    <div class="row">
                        <div class="three columns"><%= label_tag :password %></div>
                        <div class="nine columns"><%= password_field_tag :password, params[:login], class: 'u-full-width' %></div>
                    </div>
                    <div class="row">
                        <div class="three columns">&nbsp;</div>
                        <div class="nine columns"><%= submit_tag 'Log In' %></div>
                    </div>
                </div>
            <% end %>
        </div>

    </div>
</div>

conquistadors/app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @player.title %>
</p>

<p>
  <strong>Email:</strong>
  <%= @player.email %>
</p>
<% if @player.country %>
  <p>
    <strong>Country:</strong>
    <%= File.basename( @player.country.name, ".png" ).titleize %>
  </p>
<% end %>

<% if @player.country %>
  <%= link_to 'Your Country', player_country_path(@player, @player.country.id) %>
<% else %>
  <%= link_to 'Create Country', new_player_country_path(@player) %>
<% end %>
<%= link_to 'Edit', edit_player_path(@player.id) %> |
<%= link_to 'All Players', players_path %>
<%= link_to 'Trade Deals', trade_deals_path %>