conquistadors/config/routes.rb
Rails.application.routes.draw do

  resources :trade_deals

  # get '/blah' => 'static#blah'
  root to: 'static#index'

  # resources :countries

  post '/login' => :login, controller: :players
  delete '/login' => :logout, controller: :players
  resources :players do
    # get ':param' => :show, on: :member
    resources :countries
  end

  

end

conquistadors/app/models/trade_deal.rb
class TradeDeal < ActiveRecord::Base
  belongs_to :player
  belongs_to :country_resource

  before_create :set_agreed_to_false

  after_update :enact_trade

  

  # all trade deals begin as false and the creator cannot modify 'agreed' boolean 
  def set_agreed_to_false
    self.agreed = nil
  end

  def enact_trade
    # binding.pry
    buyer = self.player.country
    seller = self.country_resource.country

    if self.agreed 

      # Money exchanges occur before exchange of goods
      buyer.wealth -= self.cost
      seller.wealth += self.cost

      # Exchange of goods
      item = self.country_resource.resource

      has_item = buyer.country_resources.find do |cr|
        cr.resource_id == item.id
      end
      

      if has_item 
        item_to_add = buyer.country_resources.find_by(resource_id: item.id)
        item_to_add.quantity += self.quantity
        item_to_add.save
        item_to_subtract = seller.country_resources.find_by(resource_id: item.id)
        item_to_subtract.quantity -= self.quantity
        item_to_subtract.save
      else
        buyer.country_resources.new(resource_id: item.id, quantity: self.quantity)
      end
    end

    buyer.save
    seller.save
  end

  def decline_trade
    if !self.agreed
      self.destroy
    end
  end
end

conquistadors/app/controllers/trade_deals_controller.rb
class TradeDealsController < ApplicationController
  before_action :set_trade_deal, only: [:show, :edit, :update, :destroy]

  # GET /trade_deals
  # GET /trade_deals.json
  def index
    @trade_deals = TradeDeal.all
  end

  # GET /trade_deals/1
  # GET /trade_deals/1.json
  def show
  end

  # GET /trade_deals/new
  def new
    @trade_deal = TradeDeal.new
    @trade_deal.player_id = current_player
  end

  # GET /trade_deals/1/edit
  def edit
  end

  # POST /trade_deals
  # POST /trade_deals.json
  def create
    @trade_deal = TradeDeal.new(trade_deal_params)
    @trade_deal.player_id = current_player.id
    if current_player.country.wealth > @trade_deal.cost
      @trade_deal.save
    end
    respond_to do |format|
      if @trade_deal.save
        format.html { redirect_to @trade_deal, notice: 'Trade deal was successfully created.' }
        format.json { render :show, status: :created, location: @trade_deal }
      else
        format.html { render :new, notice: 'Not enough country wealth' }
        format.json { render json: @trade_deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trade_deals/1
  # PATCH/PUT /trade_deals/1.json
  def update
    respond_to do |format|
      if @trade_deal.update(trade_deal_params)
        format.html { redirect_to @trade_deal, notice: 'Trade deal was successfully updated.' }
        format.json { render :show, status: :ok, location: @trade_deal }
      else
        format.html { render :edit }
        format.json { render json: @trade_deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trade_deals/1
  # DELETE /trade_deals/1.json
  def destroy
    @trade_deal.destroy
    respond_to do |format|
      format.html { redirect_to trade_deals_url, notice: 'Trade deal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trade_deal
      @trade_deal = TradeDeal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trade_deal_params
      params.require(:trade_deal).permit(:player_id, :country_resource_id, :cost, :quantity, :agreed)
    end
  end

conquistadors/app/helpers/trade_deals_helper.rb
module TradeDealsHelper
end

conquistadors/app/views/trade_deals/_form.html.erb
  <% if @trade_deal.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@trade_deal.errors.count, "error") %> prohibited this trade_deal from being saved:</h2>

    <ul>
      <% @trade_deal.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

 

conquistadors/app/views/trade_deals/edit.html.erb
<h1>Editing Trade Deal</h1>

<p>Offer from <%=@trade_deal.player.name %> to buy <%=@trade_deal.quantity %> <%=@trade_deal.country_resource.resource.name %> for <%=@trade_deal.cost %> Wealth</p>

<%= form_for(@trade_deal) do |form| %>
<%= render form %>
<!-- This boolean is only avaiable to the player whose country owns this resource! -->
<% if Player.find_by_trade_deal(@trade_deal) == current_player%>
<div class="field">
  <%= radio_button('trade_deal','agreed', true) %>
  <%= label_tag(:agreed_agree, "Agree") %>
  <%= radio_button('trade_deal','agreed', false) %>
  <%= label_tag(:agreed_decline, "Decline") %>
</div>
<% end %>

<div class="actions">
  <%= form.submit "Update Trade Deal!"%>
</div>
<% end %>

<%= link_to 'Show', @trade_deal %> |
<%= link_to 'Back', trade_deals_path %>

conquistadors/app/views/trade_deals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Trade Deals</h1>

<table>
  <thead>
    <tr>
      <th>Buyer</th>
      <th>Seller</th>
      <th>Resource</th>
      <th>Cost</th>
      <th>Quantity</th>
      <th>Agreed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trade_deals.each do |trade_deal| %>
      <tr>
        <td><%= trade_deal.player.name %></td>
        <td><%= trade_deal.country_resource.country.player.name %></td>
        <td><%= trade_deal.country_resource.resource.name %></td>
        <td><%= trade_deal.cost %></td>
        <td><%= trade_deal.quantity %></td>
        <td><%= trade_deal.agreed %></td>
        <td><%= link_to 'Show', trade_deal %></td>
        <td><%= link_to 'Edit', edit_trade_deal_path(trade_deal) %></td>
        <td><%= link_to 'Destroy', trade_deal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trade deal', new_trade_deal_path %>
<%= link_to 'All Players', players_path %>

conquistadors/app/views/trade_deals/new.html.erb
<h1>New Trade Deal</h1>

<%= form_for(@trade_deal) do |form| %>
  <%= render form %>
   <div class="field">
    <%= form.label :country_resource_id %><br>
    <%= form.select :country_resource_id, CountryResource.all.collect { |r| [Resource.find(r.resource_id).name + ' from ' + Country.find(r.country_id).name.titleize.split('.')[0], r.id]} %>
  </div>

  <div class="field">
    <%= form.label :quantity %><br>
    <%= form.number_field :quantity%>
  </div>

  <div class="field">
    <%= form.label :cost %><br>
    <%= form.number_field :cost, in: 1..current_player.country.wealth  %>
  </div>
  <div class="actions">
    <%= form.submit "Create Trade Deal!" %>
  </div>
<% end %>

<%= link_to 'Back', trade_deals_path %>

conquistadors/app/views/trade_deals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Buyer:</strong>
  <%= @trade_deal.player.name %>
</p>

<p>
  <strong>Seller:</strong>
  <%= @trade_deal.country_resource.country.player.name %>
</p>

<p>
  <strong>Resource:</strong>
  <%= @trade_deal.country_resource.resource.name %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @trade_deal.cost %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @trade_deal.quantity %>
</p>

<p>
  <strong>Agreed:</strong>
  <%= @trade_deal.agreed %>
</p>

<%= link_to 'Edit', edit_trade_deal_path(@trade_deal) %> |
<%= link_to 'Back', trade_deals_path %>