conquistadors/config/routes.rb
Rails.application.routes.draw do

  resources :trade_deals

  # get '/blah' => 'static#blah'
  root to: 'static#index'

  # resources :countries

  post '/login' => :login, controller: :players
  delete '/login' => :logout, controller: :players
  resources :players do
    # get ':param' => :show, on: :member
    resources :countries
  end

  

end

conquistadors/app/models/country.rb
class Country < ActiveRecord::Base
  belongs_to :player
  has_many :country_resources
  has_many :resources, through: :country_resources

  # Add validation...employment,tax_rate cannot be more than 100 
  validates :employment, numericality: {less_than: 100}
  validates :tax_rate, numericality: {less_than: 100}


  # Active Record Callbacks!!
  before_create :set_population_and_wealth 
  after_create :set_resources

  def set_population_and_wealth
    self.population = rand(0..100)
    self.wealth = rand(0..100)
  end

  def set_resources
    resources = Resource.all
    resources.sample(rand(3..6)).each do |resource|
      assignment = self.country_resources.new({resource_id: resource.id})
      assignment.save
    end 
    self.country_resources.each do |cr|
      cr.quantity = rand(10..30)
      cr.save
    end
  end  


end

conquistadors/app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :require_login
  before_action :set_country, only: [:edit, :update, :destroy]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
    @country = Country.find(params[:id])
  end

  # GET /countries/new
  def new
    @country = Country.new
    @player = current_player
    # @country = current_player.country.new

  end

  # GET /countries/1/edit
  def edit
    @player = current_player
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)
    @player = current_player
    @country.update(player_id: @player.id)


    respond_to do |format|
      if @country.save
        format.html { redirect_to @player, notice: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    @player = current_player
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @player, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = current_player.country
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      if action_name == "index"
        params.require(:country).permit(:name, :player_id, :flag, :motto, :employment, :tax_rate, :wealth, :population)
      elsif action_name == "create"
        params.require(:country).permit(:name, :player_id, :flag, :motto, :employment, :tax_rate)
      end
    end
end

conquistadors/app/helpers/countries_helper.rb
module CountriesHelper
end

conquistadors/app/views/countries/_form.html.erb
<% if @country.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@country.errors.count, "error") %> prohibited this country from being saved:</h2>

    <ul>
    <% @country.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= form.label :name %><br>
  <%= form.select :name, Dir[Rails.root.join("app/assets/images/flags/*.png")].map { |flag| [File.basename(flag, ".png").titleize, File.basename(flag)]}%>
</div>
<div class="field">
  <%= form.label :motto %><br>
  <%= form.text_field :motto %>
</div>
<div class="field">
  <%= form.label :employment %><br>
  <%= form.text_field :employment %>
</div>
<div class="field">
  <%= form.label :tax_rate %><br>
  <%= form.text_field :tax_rate %>
</div>

conquistadors/app/views/countries/edit.html.erb
<h1>Editing Country</h1>

<%= form_for([@player, @country]) do |form| %>
  <%= render form %>
  <div class="actions">
    <%= form.submit "changing things up!" %>
  </div>
<% end %>


<%= link_to 'Back', player_country_path(@player, @country) %>

conquistadors/app/views/countries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Countries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Player</th>
      <th>Flag</th>
      <th>Motto</th>
      <th>Population</th>
      <th>Employment</th>
      <th>Tax rate</th>
      <th>Wealth</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @countries.each do |country| %>
      <tr>
        <td><%= country.name %></td>
        <td><%= country.player %></td>
        <td><%= country.flag %></td>
        <td><%= country.motto %></td>
        <td><%= country.population %></td>
        <td><%= country.employment %></td>
        <td><%= country.tax_rate %></td>
        <td><%= country.wealth %></td>
        <td><%= link_to 'Show', country %></td>
        <td><%= link_to 'Edit', edit_country_path(country) %></td>
        <td><%= link_to 'Destroy', country, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Country', new_country_path %>

conquistadors/app/views/countries/new.html.erb
<h1>New Country</h1>

<%= form_for([@player, @country]) do |form| %>
  <%= render form %>
  <div class="actions">
    <%= form.submit "create that!!!@" %>
  </div>
<% end %>

<%= link_to 'Back',  player_countries_path(@player)  %>

conquistadors/app/views/countries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= File.basename( @country.name, ".png" ).titleize %>
</p>

<p>
  <strong>Ruler:</strong>
  <%= @country.player.name %>
</p>

<p>
  <%= image_tag "flags/" + @country.name %>
</p>

<p>
  <strong>Motto:</strong>
  <%= @country.motto %>
</p>

<p>
  <strong>Population:</strong>
  <%= @country.population %>
</p>

<p>
  <strong>Employment:</strong>
  <%= @country.employment %>
</p>

<p>
  <strong>Tax rate:</strong>
  <%= @country.tax_rate %>
</p>

<p>
  <strong>Wealth:</strong>
  <%= @country.wealth %>
</p>

<strong>Resources</strong>
<ul>
  <% @country.country_resources.each do |r| %>
  <li><%=r.quantity%> <%=Resource.find(r.resource_id).name %>, Growth rate: <%= Resource.find(r.resource_id).growth_factor %>, Exchange rate: <%= Resource.find(r.resource_id).exchange_rate %></li>
  <% end %>
</ul>

<% @country.country_resources.each do |cr| %>
  <% if cr.trade_deals.any? %>
    <% cr.trade_deals.each do |deal| %>
      <%= link_to "Offer from #{deal.player.name} to buy #{deal.quantity} #{deal.country_resource.resource.name} for #{deal.cost} Wealth", edit_trade_deal_path(deal) %><br>
    <% end %>
  <% end %>
<% end %>
<br>

<% if @country.player_id == current_player.id %>
  <%= link_to 'Edit', edit_player_country_path(@country.player_id, @country.id) %>
<% end %>
<%= link_to 'Back', player_path(@country.player_id) %>